[project]
name = "pos-ai"
version = "0.1.0"
description = "POS AI is an AI-powered tool designed to assist with point-of-sale systems by leveraging natural language processing and machine learning techniques."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.1.2",
    "langchain-openai>=1.1.0",
    "langgraph>=1.0.4",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "langgraph-cli[inmem]>=0.4.7",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]